/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
export var styles = ['input.ng-dirty.ng-invalid[_ngcontent-%COMP%] {\r\n  border: 2px solid #ff0000;\r\n}\r\ninput.ng-dirty.ng-valid[_ngcontent-%COMP%] {\r\n  border: 2px solid #6bc502;\r\n}'];
